version: '3.4'

networks:
  main:
    name: itu-minitwit-network
    driver: bridge

services:
  mongodb:
    image: mongo:latest
    command: [--auth]
    environment:
      MONGO_INITDB_ROOT_USERNAME: radiator
      MONGO_INITDB_ROOT_PASSWORD: ${DB_PASSWORD}
    volumes:
      - mongodb_data_container:/data/db
    ports:
      - '27018:27017'
    networks:
      - main

  prometheus:
      image: prom/prometheus:latest
      container_name: prometheus
      volumes:
        - ./Monitoring/prometheus.prod.yml:/etc/prometheus/prometheus.yml
        - prometheus_storage:/prometheus
      ports:
        - "9090:9090"
      networks:
        - main
  
  loki:
    image: grafana/loki:latest
    container_name: loki
    volumes:
      - loki_storage:/loki
    ports:
      - 3100:3100
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - main

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    environment:
      GF_SECURITY_ADMIN_USER: radiator
      GF_SECURITY_ADMIN_PASSWORD: ${GRAFANA_PASSWORD}
      GF_SERVER_HTTP_PORT: 3001
      GF_SMTP_ENABLED: "true"
      GF_SMTP_HOST: smtp.gmail.com:587
      GF_SMTP_USER: radiator.k.devops@gmail.com
      GF_SMTP_PASSWORD: ${SMTP_PASSWORD}
      GF_SMTP_FROM_ADDRESS: radiator.k.devops@gmail.com
    volumes:
      - ./Monitoring/Grafana/provisioning/:/etc/grafana/provisioning/
      - ./Monitoring/Grafana/dashboards/:/var/lib/grafana/dashboards/
      - grafana_storage:/var/lib/grafana
    ports:
      - "9091:3001"
    depends_on:
      - prometheus
      - loki
    networks:
      - main

volumes:
  grafana_storage:
  prometheus_storage:
  loki_storage:
  mongodb_data_container:
