version: '3.4'

networks:
    main:
      driver: "overlay"

services:
  itu-minitwit-server:
    image: ${DOCKER_USERNAME}/itu-minitwit-server:latest
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: http://+:80
      ConnectionStrings__MiniTwit: ${DB_CONNECTION_STRING}
    deploy:
      replicas: 3
      update_config:
        delay: 10s
    ports:
      - '80:80'
    networks:
      - main

  itu-minitwit-web:
    image: ${DOCKER_USERNAME}/itu-minitwit-web:latest
    deploy:
      replicas: 3
      update_config:
        delay: 10s
    ports:
      - '3000:3000'
    networks:
      - main
    depends_on:
      - itu-minitwit-server
