{
 "title": "MiniTwit",
 "description": "A dashboard for monitoring the MiniTwit API.",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 23, "x": 0, "y": 0 },
   "options": {
    "content": "# Welcome to the MiniTwit Monitoring Dashboard"
   }
  },
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 } },
  {
   "title": "MinitTwit API",
   "type": "stat",
   "description": "Whether the MiniTwit API is up.",
   "gridPos": { "h": 7, "w": 3, "x": 0, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{job=\"itu-minitwit-app\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Prometheus",
   "type": "stat",
   "description": "Whether the Prometheus API is up.",
   "gridPos": { "h": 7, "w": 3, "x": 3, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{job=\"prometheus\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Avg. Request Response Time (s) [5m]",
   "type": "stat",
   "description": "The average response time for a HTTP request for the last 5 minutes.",
   "gridPos": { "h": 7, "w": 8, "x": 6, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(http_request_duration_seconds_sum[5m])) / sum(rate(http_request_duration_seconds_count[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Response Codes across all Controllers",
   "type": "bargauge",
   "description": "The sum of all HTTP codes across all controllers.",
   "gridPos": { "h": 7, "w": 9, "x": 14, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(code) (http_requests_received_total)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "System Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "Current CPU Usage",
   "type": "gauge",
   "description": "The current CPU usage in percent.",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "system_runtime_cpu_usage", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "CPU usage over Time",
   "type": "timeseries",
   "description": "The overall CPU usage of the MiniTwit API over time in percent.",
   "gridPos": { "h": 8, "w": 17, "x": 6, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    { "expr": "system_runtime_cpu_usage", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "MiniTwit Memory Usage (MB)",
   "type": "timeseries",
   "description": "The total memory usage of MiniTwit.",
   "gridPos": { "h": 7, "w": 23, "x": 0, "y": 19 },
   "targets": [
    {
     "expr": "dotnet_total_memory_bytes * 10 ^ -6",
     "legendFormat": "Memory usage over time"
    }
   ]
  },
  { "title": "Request Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "Total number of Requests Received",
   "type": "timeseries",
   "description": "The total number of requests received over all endpoints.",
   "gridPos": { "h": 8, "w": 18, "x": 0, "y": 27 },
   "targets": [
    {
     "expr": "sum(http_requests_received_total)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Requests in Progress",
   "type": "bargauge",
   "description": "The total number of request currently being processed.",
   "gridPos": { "h": 8, "w": 5, "x": 18, "y": 27 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(controller) (http_requests_in_progress{controller=\"Sim\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by(controller) (http_requests_in_progress{controller=\"Twitter\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Simulator Total Request per Endpoint",
   "type": "bargauge",
   "description": "The total number of request for each endpoint of the Simulator API.",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 35 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(endpoint) (http_requests_received_total{controller=\"Sim\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Twitter Total Request per Endpoint",
   "type": "bargauge",
   "description": "The total number of request for each endpoint of the Twitter API.",
   "gridPos": { "h": 8, "w": 12, "x": 11, "y": 35 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(endpoint) (http_requests_received_total{controller=\"Twitter\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Simulator Request Errors per HTTP Code",
   "type": "timeseries",
   "description": "The total number of request errors per HTTP code.",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 43 },
   "targets": [
    {
     "expr": "sum by(code) (http_requests_received_total{code=~\"4[0-9]{2}|5[0-9]{2}\", controller=\"Sim\"})",
     "legendFormat": "{{code}}"
    }
   ]
  },
  {
   "title": "Twitter Request Errors per HTTP Code",
   "type": "timeseries",
   "description": "The total number of request errors per HTTP code.",
   "gridPos": { "h": 8, "w": 12, "x": 11, "y": 43 },
   "targets": [
    {
     "expr": "sum by(code) (http_requests_received_total{code=~\"4[0-9]{2}|5[0-9]{2}\", controller=\"Twitter\"})",
     "legendFormat": "{{code}}"
    }
   ]
  },
  {
   "title": "Simulator Successful Request per HTTP Code",
   "type": "timeseries",
   "description": "The number of successful request per response code.",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 51 },
   "targets": [
    {
     "expr": "sum by(code) (http_requests_received_total{code=~\"2[0-9]{2}\", controller=\"Sim\"})",
     "legendFormat": "{{code}}"
    }
   ]
  },
  {
   "title": "Twitter Successful Request per HTTP Code",
   "type": "timeseries",
   "description": "The number of successful request per response code.",
   "gridPos": { "h": 8, "w": 12, "x": 11, "y": 51 },
   "targets": [
    {
     "expr": "sum by(code) (http_requests_received_total{code=~\"2[0-9]{2}\", controller=\"Twitter\"})",
     "legendFormat": "{{code}}"
    }
   ]
  }
 ]
}