global:
  scrape_interval: 15s
  evaluation_interval: 15s

  external_labels:
    monitor: 'codelab-monitor'

rule_files:
  - 'prometheus.rules.yml'

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['prometheus:9090']

  - job_name: 'itu-minitwit-app'
    scrape_interval: 5s
    static_configs:
      - targets: ['128.199.3.151:80']
