{
 "title": "MiniTwit Logging",
 "description": "Logging of the MiniTwit application",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 23, "x": 0, "y": 0 },
   "options": {
    "content": "# Welcome to the MiniTwit Logging Dashboard"
   }
  },
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 } },
  {
   "title": "Log level distribution [5m]",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 19, "x": 0, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(level) (rate({app=\"minitwit\"} | json level=\"level\" [5m]))",
     "legendFormat": "{{level}}"
    }
   ]
  },
  { "title": "MiniTwit Dashboards", "type": "dashlist", "gridPos": { "h": 6, "w": 4, "x": 19, "y": 3 } },
  {
   "title": "MiniTwit Logs [last 500 lines]",
   "type": "logs",
   "description": "All logs recorded from the MiniTwit backend.",
   "gridPos": { "h": 13, "w": 23, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "{app=\"minitwit\"} | json level=\"level\", method=\"RequestMethod\", path=\"RequestPath\", code=\"StatusCode\", name=\"Application\", env=\"Environment\", message=\"Message\", action=\"ActionName\" | line_format `[{{.level}}] {{.name}} ({{.env}}): {{.message}}`",
     "maxLines": 250,
     "resolution": 1
    }
   ]
  },
  { "title": "Errors", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 } },
  {
   "title": "Logged Errors and Warnings [last 500 lines]",
   "type": "logs",
   "gridPos": { "h": 10, "w": 23, "x": 0, "y": 23 },
   "targets": [
    {
     "expr": "{app=\"minitwit\"} | json message=\"Message\", level=\"level\", name=\"Application\", env=\"Environment\", action=\"ActionName\", path=\"RequestPath\" | line_format `[{{.level}}] {{.action}} ({{.env}}) @ \"{{.path}}\": {{.message}}` | level = `error`",
     "maxLines": 500
    },
    {
     "expr": "{app=\"minitwit\"} | json message=\"Message\", level=\"level\", name=\"Application\", env=\"Environment\", action=\"ActionName\", path=\"RequestPath\" | line_format `[{{.level}}] {{.action}} ({{.env}}) @ \"{{.path}}\": {{.message}}` | level = `warning`",
     "maxLines": 500
    }
   ]
  }
 ]
}